image:
  - ubuntu:latest
stages:
  - test
default:
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    #- apk update 
    #- apk add python py-pip
test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest

