image: "python:3.8.7-alpine"
stages:
  - test
default:
  before_script:
    #- apt-get update -qy
    #- apt-get install -y python3.8 python3-pip
    - apk update
    - apk add --no-cache python3.8 py3-pip py-numpy
test:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - pytest --cov=src/ test/
    - coverage html
