variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - analysis
  - test

#frontend-lint:
#  stage: analysis
#  image: node:alpine
#  before_script:
#    - cd frontend
#    - apk add --no-cache git
#    - yarn
#  script:
#    - yarn lint
#
#lint-python:
#  stage: analysis
#  image: python:3.8.7-buster
#  before_script:
#    - cd backend
#    - pip3 install isort flake8
#  script:
#    - flake8
#    - isort -rc .

backend-test:
  stage: test
  image: python:3.6.13-buster
  before_script:
    - apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
    - apt-get install libcblas-dev
    - apt-get install libhdf5-dev
    - apt-get install libhdf5-serial-dev
    - apt-get install libatlas-base-dev
    - apt-get install libjasper-dev 
    - apt-get install libqtgui4 
    - apt-get install libqt4-test

    - cd backend
    - pip3 install -r requirements.txt
  script:
    - python -m pytest tests/

