image: python:3.8.7-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - test

before_script:
  - python -V  
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - pytest --cov=backend/ --cov=frontend/ 
    - coverage html
    # - pip install tox flake8  # you can also use tox
    # - tox -e py36,flake8
