image: "ubuntu"
stages:
  - test
default:
  before_script:
    - apt-get update -qy
    - apt-get install -y python python3-pip
    #- apk update 
    #- apk add python py-pip
test:
  stage: test
  script:
    - python -m pip install -r requirements.txt
    - python -m pytest

